= LuaTeX Performance

We noticed degrading performance on long documents processed with LuaTeX. This
simplified sample is a minimal working example to show that once the document is
in the four-figure page range, the LuaTeX engine drops in performance.

We have the impression that this has not always been the case. Currently, it
seems that some time in late 2021 a change has been made that the processing
speed became worse.

Run `lualatex test` to build the sample.

`test.tex` defines the testing framework and time measuring. It includes
`testcase.tex` several hundred times. Change number of iterations by adjusting
the loop in `test.tex`. `testcase.tex` is a sample document of arbitrary
complexity. In the standard case, it consists of text generated by the
link:https://ctan.org/pkg/lipsum?lang=de[lipsum] package.

At the end of processing, `test.tex` prints a table with the timing results for
each lap. A lap consists of (by default) 50 inclusions of `testcase.tex`. The
times printed for each lap are the number of seconds it took to process this lap
and the number of seconds elapsed since the start. Time measuring is done by
calling Lua's `os.time()` function, which returns whole seconds.
